version: "3.7"

services:

  database_mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arch
      MONGO_INITDB_ROOT_PASSWORD: 12345
  redis-server: 
    image: 'redis'
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: transacao_api
    ports:
      - 3333:3333
    volumes:
      - .:/user/app
    links:
      - database_mongo
    depends_on:
      - database_mongo