version: "3.7"

services:

  database_mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arch
      MONGO_INITDB_ROOT_PASSWORD: 12345
  redis-server: 
    image: 'redis'
    ports:
      - "6379:6379"
  transacao_api:
    build: 
      context: ./transacao-api
      dockerfile: Dockerfile
    container_name: transacao_api
    ports:
      - 3333:3333
    volumes:
      - ./transacao_api:/user/transacao_api
    links:
      - database_mongo
      - redis-server
    depends_on:
      - database_mongo
      - redis-server