version: "3.7"

services:

  database-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arch
      MONGO_INITDB_ROOT_PASSWORD: 12345
  redis-server: 
    image: 'redis'
    ports:
      - "6379:6379"
  transacao-api:
    build: 
      context: ./transacao-api
      dockerfile: Dockerfile
    container_name: transacao-api
    ports:
      - 3333:3333
    volumes:
      - ./transacao-api:/user/transacao-api
    links:
      - database-mongo
      - redis-server
    depends_on:
      - database-mongo
      - redis-server
  saldo-api:
    build: 
      context: ./saldo-api
      dockerfile: Dockerfile
    container_name: saldo-api
    ports:
      - 3331:3331
    volumes:
      - ./saldo-api:/user/saldo-api
    links:
      - database-mongo
      - redis-server
    depends_on:
      - database-mongo
      - redis-server